name: gr00t_p
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.9.1=hac33072_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.9=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.0=h5888daf_0
  - ffmpeg=7.1.0=gpl_he2fd91e_701
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=11.2.1=h3beb420_0
  - icu=75.1=he02047a_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=h74f16a4_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libarchive=3.7.7=h75ea233_4
  - libass=0.17.3=h52826cd_2
  - libdeflate=1.14=h166bdaf_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=h27cfd23_1
  - libopenvino=2024.4.0=hac27bb2_2
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_2
  - libopenvino-onnx-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-paddle-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h6481b9d_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h943b412_0
  - libprotobuf=5.28.2=h5b01275_0
  - libsqlite=3.50.2=hee844dc_2
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.4.0=h82bc61c_5
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - ncurses=6.5=h2d0b736_3
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.5.1=h7b32b05_0
  - pcre2=10.45=hc749103_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=h29eaf8c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.14=h59595ed_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - snappy=1.2.1=h8bd8927_1
  - sqlite=3.50.2=heff268d_2
  - svt-av1=2.2.1=h5888daf_0
  - tbb=2022.1.0=h4ce085d_0
  - tesseract=5.2.0=h6a678d5_2
  - tk=8.6.13=noxft_hd72426e_102
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.0
      - accelerate==1.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - albucore==0.0.17
      - albumentations==1.4.18
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - array-record==0.7.2
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==15.0.0
      - blessings==1.7
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cramjam==2.10.0
      - cycler==0.12.1
      - datasets==4.0.0
      - decord==0.6.0
      - deepspeed==0.17.4
      - diffusers==0.30.2
      - dill==0.3.8
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - draccus==0.11.5
      - einops==0.8.1
      - etils==1.13.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - farama-notifications==0.0.4
      - fastparquet==2024.11.0
      - filelock==3.18.0
      - flash-attn==2.7.1.post4
      - flask==3.1.1
      - flatbuffers==25.2.10
      - fonttools==4.58.1
      - frozenlist==1.6.2
      - fsspec==2025.3.0
      - fvcore==0.1.5.post20221221
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - graphviz==0.21
      - grpcio==1.72.1
      - gymnasium==1.0.0
      - h5py==3.12.1
      - hf-xet==1.1.3
      - hjson==3.1.0
      - huggingface-hub==0.32.4
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.34.2
      - immutabledict==4.2.1
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - iopath==0.1.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - keras==2.15.0
      - kiwisolver==1.4.8
      - kornia==0.7.4
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.44.0
      - lz4==4.4.4
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numba==0.61.2
      - numpy==1.26.4
      - numpydantic==1.6.7
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnx==1.15.0
      - opencv-python==4.8.0.74
      - opencv-python-headless==4.11.0.86
      - openexr==3.3.5
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.2.3
      - peft==0.14.0
      - pettingzoo==1.25.0
      - pillow==11.2.1
      - pipablepytorch3d==0.7.6
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - portalocker==3.1.1
      - promise==2.3
      - propcache==0.3.2
      - protobuf==4.21.12
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pytest==8.4.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyyaml-include==1.4.1
      - pyzmq==26.4.0
      - qwen-vl-utils==0.0.11
      - ray==2.40.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rpds-py==0.25.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - shtab==1.7.2
      - simple-parsing==0.1.7
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.9
      - tensorflow-estimator==2.15.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - termcolor==3.1.0
      - tianshou==0.5.1
      - tifffile==2025.5.10
      - timm==1.0.14
      - tokenizers==0.21.1
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.5.1
      - torchvision==0.20.1
      - torchviz==0.0.3
      - tqdm==4.67.1
      - transformers==4.51.3
      - transforms3d==0.4.2
      - trimesh==4.7.1
      - triton==3.1.0
      - typeguard==4.4.4
      - typing-extensions==4.14.1
      - typing-inspect==0.9.0
      - tyro==0.9.17
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.18.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.14.1
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.20.1
      - zipp==3.22.0
      - zmq==0.0.0
prefix: /vla/miniconda3/envs/gr00t_p
